### ISSUE TITLE
Arrow keys are not navigating the tree

### ISSUE THREAD

**Issue by ipstone** [takaxp/org-tree-slide#25] opened 2018-02-08 16:58 UTC
I have latest orgmode installed on Emacs 25.3. 
After installing org-tree-slide from MELPA, somehow the org-tree-slide-mode doesn't allow navigate orgmode file with the arrow keys. Is there something wrong, or settings need to be setup? 

Thanks
-- Ipstone

**Comment by takaxp** [comment] 2018-02-08 17:09
Hi Ipstone,

I changed the normal key bind to change slides some years ago.
The current setting is assigned to “C-<“ or “C->” to change slides.

    (define-key map (kbd "C-<") 'org-tree-slide-move-previous-tree)
    (define-key map (kbd "C->") 'org-tree-slide-move-next-tree)

If you want to change the setting to use “<right>” or “<left>”, then
copy & paste the following code to you init.el

(with-eval-after-load "org-tree-slide"
  (define-key org-tree-slide-mode-map (kbd "<left>") 'org-tree-slide-move-previous-tree)
  (define-key org-tree-slide-mode-map (kbd "<right>") 'org-tree-slide-move-next-tree))

I hope this setting will resolve your issue.

Best,
Takaaki

**Comment by takaxp** [comment] 2018-02-21 07:38
This issue will be closed soon.

**Comment by Thaodan** [comment] 2018-03-12 14:59
The issue is thats thats verry US keyboard layout centric on any layout thats not qwerty this keybind is not usable.

**Comment by takaxp** [comment] 2018-03-12 22:09
Rights. I use US keyboard. But anyone can change the keybindings through `org-tree-slide-mode-map`. Any suggestions for non-qwerty keyboard user?

**Comment by Thaodan** [comment] 2018-03-13 01:27
, and . key 

Or . And -

It's about the same keys compared to us keyboard.

**Comment by takaxp** [comment] 2018-03-13 01:38
Thanks. I see Dvorak layout[*1].
OK, I'll reflect this to README 👍 

[*1] https://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard

**Comment by takaxp** [comment] 2018-03-13 02:43
@ipstone any additional comments on this? otherwise I'll close this issue.

**Closed** 2018-12-14 07:56 UTC

**Comment by ipstone** [comment] 2019-03-22 16:13
thanks!

**Comment by refaelsh** [comment] 2023-05-13 20:15
> (with-eval-after-load "org-tree-slide" (define-key org-tree-slide-mode-map (kbd "<left>") 'org-tree-slide-move-previous-tree) (define-key org-tree-slide-mode-map (kbd "<right>") 'org-tree-slide-move-next-tree))

This solution does not work when using Evil mode. I don't know what is so special about the arrow key while using Evil mode. If I use your code sample with any other key, it works.
